#!/usr/bin/env python

import optparse		# For cmslpc/cmssw compatibility...
import os
import shutil

import ROOT

treeName = 'tree'

directory = "/eos/uscms/store/user/bjr/trees/"

#var = 'hadWcandtau21'

var = 'lep2Ddr'

# (lep2Drel > 25 || lep2Ddr > 0.5)

cut = "(leppt > 25 && numjets > 2 && cuts[2] > 0 && hadWcandpt > 200 && hadWcandmass > 50 && hadWcandmass < 120)"

lumi = 19748.

def makePlot(plot, plotName, filename, color, weight):
	print filename
	chain = ROOT.TChain('tree')
	chain.Add(filename)
	plot.SetLineColor(color)
	chain.Draw(var+">>" + plotName, str(weight)+"*"+cut, "goff")
	plot.Scale(lumi)
	plot.SetStats(0)
	plot.SetLineWidth(3)
	return plot

def main():

	bins = 100
	start = 0
	end = 5

	w1Plot = ROOT.TH1F('wjets_plot', 'wjets_plot', bins, start, end)
	w2Plot = ROOT.TH1F('wjets2_plot', 'wjets2_plot', bins, start, end)
	w3Plot = ROOT.TH1F('wjets3_plot', 'wjets3_plot', bins, start, end)
	w4Plot = ROOT.TH1F('wjets4_plot', 'wjets4_plot', bins, start, end)
	ttbarFullPlot = ROOT.TH1F('ttbar_dileptonic', 'ttbar_dileptonic', bins, start, end)
	ttbarSemiPlot = ROOT.TH1F('ttbar_semileptonic', 'ttbar_semileptonic', bins, start, end)

	print "Making plots."
	for path, dir, files in os.walk(directory):
		if path == directory:
			for filename in files:
				if 'W1JetsToLNu' in filename:
					w1Plot = makePlot(w1Plot, 'wjets_plot', os.path.join(path, filename), ROOT.TColor.kGreen, 6662.8 / 23141598.)
				elif 'W2JetsToLNu' in filename:
					w2Plot = makePlot(w2Plot, 'wjets2_plot', os.path.join(path, filename), ROOT.TColor.kGreen, 2159.2 / 34044921.)
				elif 'W3JetsToLNu' in filename:
					w3Plot = makePlot(w3Plot, 'wjets3_plot', os.path.join(path, filename), ROOT.TColor.kGreen, 640.4 / 15539503.)
				elif 'W4JetsToLNu' in filename:
					w4Plot = makePlot(w4Plot, 'wjets4_plot', os.path.join(path, filename), ROOT.TColor.kGreen, 264.0 / 13382803.)
				elif 'TTJets_FullLept' in filename:
					ttbarFullPlot = makePlot(ttbarFullPlot, 'ttbar_dileptonic', os.path.join(path, filename), ROOT.TColor.kRed + 2, 25.17/12119013.)
				elif 'TTJets_SemiLept' in filename:
					ttbarSemiPlot = makePlot(ttbarSemiPlot, 'ttbar_semileptonic', os.path.join(path, filename), ROOT.TColor.kRed, 107.7/25424818.)

	w1Plot.Add(w2Plot)
	w1Plot.Add(w3Plot)
	w1Plot.Add(w4Plot)

	canvas = ROOT.TCanvas('canvas', 'canvas', 1200, 800)
	canvas.cd()

	plot = w1Plot
	plot.Draw()
	ttbarSemiPlot.Draw("same")

	legend = ROOT.TLegend()
	legend.AddEntry(plot, 'W+Jets Semileptonic MC')
	legend.AddEntry(ttbarSemiPlot, 'TTbar Semileptonic MC')
	legend.Draw()

	ttbarFullPlot.Draw("same")

	plot.SetTitle("Pre-Tagged lep2Ddr")
	plot.GetXaxis().SetTitle("lep2Ddr")
	plot.GetYaxis().SetTitle("Events")

	canvas.SaveAs("lep2Ddr_plots.png")
	canvas.SaveAs("lep2Ddr_plots.pdf")

if __name__ == '__main__':
	main()		
