#!/usr/bin/env python

import os
import shutil

def main():
	root = "/uscms_data/d3/bjr/zprime/hadronic/analysis/zprime/working/preselection/"
	try:
		shutil.rmtree("plots")
	except:
		pass
	os.mkdir("plots")
	for path, dirs, files in os.walk("../cuts/"):
		for file in files:
			if file.count("_") == 5:
				name = file[:file.rfind(".")]
				location = os.path.join(root, name)
				os.mkdir("plots/" + name)
				os.system("scp bjr@cmslpc-sl5.fnal.gov:" + location + "/plots/" + name + ".png plots/" + name + "/stage1_plot.png")
				os.system("scp bjr@cmslpc-sl5.fnal.gov:" + location + "/output.log" + " plots/" + name + "/stage1_output.log")
				os.system("scp bjr@cmslpc-sl5.fnal.gov:" + location + "/bprime/plots/bprime.png" + " plots/" + name + "/stage2_bprime_plot.png")
				os.system("scp bjr@cmslpc-sl5.fnal.gov:" + location + "/bprime/output.log" + " plots/" + name + "/stage2_bprime_output.log")
				os.system("scp bjr@cmslpc-sl5.fnal.gov:" + location + "/tprime/plots/tprime.png" + " plots/" + name + "/stage3_tprime_plot.png")
				os.system("scp bjr@cmslpc-sl5.fnal.gov:" + location + "/tprime/output.log" + " plots/" + name + "/stage3_tprime_output.log")

				# Grab the sidebands.
				os.system("scp bjr@cmslpc-sl5.fnal.gov:" + location + "_sideband_b/plots/" + name + "_sideband_b.png" + " plots/" + name + "/stage4_sideband_b_plot.png")
				os.system("scp bjr@cmslpc-sl5.fnal.gov:" + location + "_sideband_b/output.log" + " plots/" + name + "/stage4_sideband_b_output.log")
				os.system("scp bjr@cmslpc-sl5.fnal.gov:" + location + "_sideband_w/plots/" + name + "_sideband_w.png" + " plots/" + name + "/stage5_sideband_w_plot.png")
				os.system("scp bjr@cmslpc-sl5.fnal.gov:" + location + "_sideband_w/output.log" + " plots/" + name + "/stage5_sideband_w_output.log")
				os.system("scp bjr@cmslpc-sl5.fnal.gov:" + location + "_sideband_bw/plots/" + name + "_sideband_bw.png" + " plots/" + name + "/stage6_sideband_bw_plot.png")
				os.system("scp bjr@cmslpc-sl5.fnal.gov:" + location + "_sideband_bw/output.log" + " plots/" + name + "/stage6_sideband_bw_output.log")
		
if __name__ == '__main__':
	main()
